{% set name = "megnet" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/megnet-{{ version }}.tar.gz
  sha256: 0c2de597860fa3caeefc3591f01fe48e8cc70adbda812f5b72a47c3eb6361a99

build:
  entry_points:
    - meg = megnet.cli.meg:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - monty
    - numpy
    - pymatgen >=2019.10.4
    - python >={{ python_min }}
    - scikit-learn
    - tensorflow

test:
  imports:
    - megnet
  commands:
    - pip check
    - meg --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/megnet/
  summary: MatErials Graph Networks for machine learning of molecules and crystals.
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - jan-janssen
